### ISSUE TITLE
Face detection works incorrect.

### ISSUE THREAD

**Issue by vardan007** [googlesamples/android-vision#126]
Face detector is detecting extra face(see attached image)

Used this configs:

gradle -> compile 'com.google.android.gms:play-services-vision:9.2.0'

face detector -> 
```
        com.google.android.gms.vision.face.FaceDetector detector = new         com.google.android.gms.vision.face.FaceDetector.Builder(context)
                .setTrackingEnabled(false)
                .setMode(com.google.android.gms.vision.face.FaceDetector.ACCURATE_MODE)
                .build();

        Detector<Face> safeDetector = new SafeFaceDetector(detector);
```

![screen shot 2016-09-05 at 12 14 03 pm](https://cloud.githubusercontent.com/assets/20239063/18241535/c7be601a-7362-11e6-9e5a-758eef461701.png)
![face_detection_test_image](https://cloud.githubusercontent.com/assets/20239063/18241554/df6da2d4-7362-11e6-843d-e0fc7b20c44b.jpg)

**Comment by pm0733464** [comment]
Sorry about that.  False positive detections are possible, and we have seen cases like this before.  With faceTracking = false we use a confidence threshold of 0.75, so the detector apparently had at least a 75% confidence in this case.  Unfortunately, there isn't any workaround at this time (note: setting faceTracking = true would make this problem worse, since the setting uses a lower confidence threshold).

We will look to improve this in a future release.

**Comment by vardan007** [comment]
ok thanks :)

**Comment by rareserban** [comment]
Hello, where can I find the confidence thresholds ? For example high accuracy detection confidence threshold for points and landmarks?

**Comment by yurik94** [comment]
> Hello, where can I find the confidence thresholds ? For example high accuracy detection confidence threshold for points and landmarks?

Up.

I think we have to move to the new Firebase SDK.
