### ISSUE TITLE
CameraSourcePreview / GraphicsOverlay right padding

### ISSUE THREAD

**Issue by Aeefire** [googlesamples/android-vision#4]
Hello folks,

I've been testing the library on a OnePlus One (1080x1920).

However, my camera preview (or more specifically the GraphicOverlay) gets a padding on the right (or below, it kinda seems to depend on how i set the requested preview size).

According to the View Hierarchy Dump, the CameraSourcePreview has the correct size (1080x1920), but the GraphicOverlay has its width somehow reduced to 1037 instead of the correct 1080.

The requested preview size is : (1024, 768)

Anyone noticed something similiar? Sadly I can't test it on a device with a different resolution atm.

Any solution to this or known fix? Thanks in advance

**Comment by pm0733464** [comment]
There are two different sizes that the code needs to consider: the camera preview size and the view size (e.g., the screen size).  It needs to ensure that the scale and aspect ratio of the graphic overlay match that of the displayed camera preview, which can require some extra padding.  See the onLayout code in CameraSourcePreview:

https://github.com/googlesamples/android-vision/blob/master/face/FaceTracker/app/src/main/java/com/google/android/gms/samples/vision/face/facetracker/ui/camera/CameraSourcePreview.java#L126

The camera preview size aspect ratio may be different from the aspect ratio of your phone's screen.  The camera source preview code deals with this by sizing the graphic overlay to have the same aspect ratio as the camera preview size, but sizes it so that it fits within the display.    I'm guessing that you'll also see a small black bar on the right of the camera preview which corresponds to the 43 pixel width reduction in the GraphicOverlay, which was required to fit the preview onto the screen.

Note that even though you requested 1024x768 as the preview size, the size used will match a resolution that the camera hardware supports (which may or may not be 1024x768, but it will be the closest resolution that the camera hardware supports).

**Comment by Aeefire** [comment]
This sounds reasonable and is more or less what I expected.
Thanks for that.

 But isn't it more common practice to crop the preview picture such that the preview is actually really fullscreen ? This would prevent ugly / black white bars. Especially since it isn't of major importance what is on the frame as long as the to-be-recognized object is reasonably well viewable.

**Comment by pm0733464** [comment]
The CameraSourcePreview and GraphicOverlay are part of the example code rather than being included in the API.  These are intended to be more along the lines of a "Hello World" implementation rather than official functionality.  Feel free to copy and modify these classes to add better cropping behavior in your app.

**Comment by wapegomes** [comment]
Hi! To change the preview stop fullscreen is necessary to make some changes. Following the example in class CameraSourcePreview.java you must remove or comment on the code below:
    If (childHeight> layoutHeight) {
         ChildHeight = layoutHeight;
         ChildWidth = (int) (((float) layoutHeight / (float) height) * width);
    }

After this run well. Recalling that the preview in the layout must be assigned match_parent.
