### ISSUE TITLE
No barcode detected

### ISSUE THREAD

**Issue by Crustus** [googlesamples/android-vision#8]
Hi,

I'm developing app using barcode reader and currently I'm using ZBar.
I copied this sample project.
Face detection works perfectly.
But when I try scan EAN-13 (or other barcodes) it shows nothin. Even no method call to updateItem() in Factory.

Here are two images
first from this sample
![barcode](https://cloud.githubusercontent.com/assets/8823045/9313367/d7ce6c4e-4522-11e5-9382-0b00a1072245.png)

sencond from my app using ZBar and it detects barcode
![barcode_zbar](https://cloud.githubusercontent.com/assets/8823045/9313379/ecd2c25c-4522-11e5-97df-1fa88fe21efa.png)

I can provide more info or do more tests if needed.
ZBar is not working all the time perfectly so therefore I'm looking for other possible library

EDIT: I made more testing and QR code it reads good, but 1D codes very rarely

**Comment by Gericop** [comment]
This might be a focus issue, try this fix until Google releases an update to the API which allows one to set the AF mode:
https://gist.github.com/Gericop/7de0b9fdd7a444e53b5a

**Comment by abhirav** [comment]
Where can I find the callback method after barcoded is scanned?
I want to pass barcode data to new screen, how can I do that?

**Comment by pm0733464** [comment]
The callback method is delivered to an instance of Tracker<Barcode> via its onUpdate method.  In the MultiTracker demo, this is in the GraphicTracker class.  See also this question on stackoverflow:

http://stackoverflow.com/questions/32021193/how-to-capture-barcode-values-using-the-new-barcode-api-in-google-play-services/32029162#32029162

If you only need to handle barcodes in your app (and not faces), this could be simplified by changing GraphicTracker to inherit from Tracker<Barcode> rather than being generic.

**Comment by abhirav** [comment]
Thanks. It worked :).
